name: spectrome
channels:
  - conda-forge
dependencies:
  - python=3 #or any python 3 should work
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - scikit-learn
#  - nose # for unit testing
#  - nodejs==11.9.0
#  - ipywidgets
#  - vtk==8.1.1
  - pip:
    - deepdish
#    - emcee==3.0rc2
#    - great-expectations
#    - mayavi
#    - nibabel
    - nitime
#    - PyQt5
    - python-csv
#    - pysurfer
#    - sklearn
    - tqdm==4.30.0